<?php

namespace Blogger\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostBlogRepository extends EntityRepository
{
    public function findAllOrderedByDateDesc()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT b FROM BloggerBlogBundle:PostBlog b ORDER BY b.created DESC')
            ->getResult();
    }
}