security:
    firewalls:
        secured_area:
            #il firewall viene attivato quando la richiesta in arrivo corrisponde alla regexp su pattern
            #pattern (^/) corrisponderà a ogni richiesta in arrivo. Il fatto che il firewall venga attivato 
            #non significa tuttavia che venga visualizzato il box di autenticazione con nome utente e 
            #password per ogni URL. Per esempio, qualunque utente può accedere a /foo senza che venga 
            #richiesto di autenticars
            pattern:    ^/ 
            #è abilitato l'accesso all'utente anonimo per tutti i path diversi da quelli che corrispondono
            #alla sezione access_control. Se anonymus viene tolto allora per qualsiasi richiesta verrà
            #chiesto all'utente di autenticarsi
            anonymous: ~
#            http_basic:
#                realm: "Area demo protetta"
            form_login:
                login_path:  /login
                check_path:  /login_check
                
            logout:
                path:   /logout
                target: /
#        admin_area:
#            pattern:    ^/admin
#            http_basic:
#                realm: "Area protetta"
    #access_control dice che qualsiasi URL che corrispondono allo schema dell'espressione regolare ^/admin 
    #(cioè /admin o qualunque URL del tipo /admin/*) richiede il ruolo ROLE_ADMIN.I ruoli sono la base per 
    #la maggior parte delle autorizzazioni: un utente può accedere /admin/foo solo se ha il ruolo ROLE_ADMIN.
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        
    #Nella configurazione sopra, gli utenti con ruolo ROLE_ADMIN avranno anche il ruolo ROLE_USER. 
    #Il ruolo ROLE_SUPER_ADMIN ha ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH e ROLE_USER (ereditati da ROLE_ADMIN).
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
    
    providers:
        administrators:
            #entity: { class: BloggerUserBundle:User, property: username }
            #se non viene specificata la proprietà da utilizzare per recuperare l'utente in fase di 
            #login, viene utilizzato il metodo loadUserByUsername della classe UserRepository
            #per l'autenticazione (che in questo caso utilizza si username che email come username)
            entity: { class: BloggerUserBundle:User}
        
        #questo user provider indica che ci sono due utenti con due specifici ruoli (in_memory sta ad indicare che)
        #non gli utenti non provengono da una base di dati ma da un file di confogurazione
        #in_memory:
        #    users:
        #        ryan:  { password: bb87a29949f3a1ee0559f8a57357487151281386, roles: 'ROLE_USER' }
        #        admin: { password: 44060752d7f7ae069c8187120455195325af0cca, roles: 'ROLE_ADMIN' }

    encoders:
       # Symfony\Component\Security\Core\User\User: plaintext
        Blogger\UserBundle\Entity\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false