<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120906145014 extends AbstractMigration
{
    public function up(Schema $schema)
    {
         // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("INSERT INTO `users_blog` (`id`, `username`, `salt`, `password`, `email`, `is_active`) VALUES
(3, 'ricfrank', '25983192c04aeb0c20c8d81945f7b853', '1dde7f93ec7877c934b5aeb5fdcec4667b19b1e8', 'riccardo.franconi@gmail.com', 1)");


    }

    public function down(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DELETE FROM `lebowskienico`.`users_blog` WHERE `users_blog`.`id` = 3");


    }
}
